language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
# command to run tests
script: 
  - cd pybsn/test; nosetests --with-coverage
  - python3 setup.py test
after_success: 
  - coveralls
