language: python
python:
  # betamax on py2 produces brokenness; we want to rip it out, but
  # for now let's run at least the python 3 unit tests
  - "2.7"
  - "3.5"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
# command to run tests
script: 
  - cd test && nosetests --with-coverage
after_success: 
  - coveralls
